package vista;

import simulacion.MotorSimulacion;
import simulacion.Evento;
import dao.ProductoDAO;
import modelo.Producto;
import javax.swing.*;
import java.awt.*;
import java.util.Date;

public class VentanaPrincipal extends JFrame {
    private JTextArea txtLog = new JTextArea(8, 50);
    private InventarioTableModel modeloTabla = new InventarioTableModel();
    private JTable tablaInventario = new JTable(modeloTabla);
    private PanelGrafica panelGrafica = new PanelGrafica();
    private JButton btnIniciar = new JButton("Iniciar");
    private JButton btnDetener = new JButton("Detener");
    private JSlider sliderVelocidad = new JSlider(50, 2000, 500);
    private MotorSimulacion motor;
    private ProductoDAO dao = new ProductoDAO();

    public VentanaPrincipal() {
        setTitle("Sistema Inteligente de Inventarios");
        setSize(1000, 700);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout(5, 5));

        // Norte: controles
        JPanel pnlControles = new JPanel();
        pnlControles.add(btnIniciar);
        pnlControles.add(btnDetener);
        pnlControles.add(new JLabel("Velocidad:"));
        pnlControles.add(sliderVelocidad);
        add(pnlControles, BorderLayout.NORTH);

        // Centro: Split panel con tabla y gráfica
        JSplitPane split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        split.setLeftComponent(new JScrollPane(tablaInventario));
        split.setRightComponent(panelGrafica);
        split.setDividerLocation(400);
        add(split, BorderLayout.CENTER);

        // Sur: log
        txtLog.setEditable(false);
        add(new JScrollPane(txtLog), BorderLayout.SOUTH);

        // Cargar productos iniciales
        modeloTabla.setProductos(dao.listarTodos());
        for (Producto p : dao.listarTodos()) {
            panelGrafica.agregarSerie(p.getNombre());
        }

        btnIniciar.addActionListener(e -> iniciarSimulacion());
        btnDetener.addActionListener(e -> { if (motor!= null) motor.detener(); });
        sliderVelocidad.addChangeListener(e -> {
            if (motor!= null) motor.setVelocidad(sliderVelocidad.getValue());
        });
    }

    private void iniciarSimulacion() {
        txtLog.setText("");
        motor = new MotorSimulacion() {
            @Override
            protected void process(java.util.List<Evento> eventos) {
                for (Evento e : eventos) {
                    String log = e.getTipo() + ": " + e.getCantidad() + " " +
                                 e.getProducto().getNombre() + " | Stock: " +
                            e.getProducto().getPrecio() +
                                 e.getProducto().getStockActual();
                    txtLog.append(log + "\n");

                    // Actualizar tabla
                    modeloTabla.actualizarProducto(e.getProducto());

                    // Actualizar gráfica
                    panelGrafica.agregarPunto(
                        e.getProducto().getNombre(),
                        java.sql.Timestamp.valueOf(e.getFecha()),
                        e.getProducto().getStockActual()
                    );
                }
            }
        };
        motor.execute();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        SwingUtilities.invokeLater(() -> new VentanaPrincipal().setVisible(true));

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
